# Session 11 commits: plan 08 (worry postponement) and plan 09's spine.
#
# ASCII ONLY. Windows PowerShell 5.1 reads a script as ANSI unless it has a
# BOM, so a single em dash in a here-string gets written into the repo doubly
# encoded. Check with:
#   python -c "print(sum(1 for b in open('progress/commit-session-11.ps1','rb').read() if b>127))"
#
# Safe to re-run: every step skips when there is nothing staged.

$ErrorActionPreference = 'Stop'
Set-Location (Join-Path $PSScriptRoot '..')

function Commit-Step {
    param(
        [string[]] $Paths,
        [string]   $Message,
        [string]   $Todo
    )

    foreach ($p in $Paths) {
        if (Test-Path $p) { git add -A -- $p }
    }

    if (git diff --cached --quiet) {
        Write-Host "skip  $Message" -ForegroundColor DarkGray
        return
    }

    git commit -q -m $Message
    $sha = (git rev-parse --short HEAD)
    Write-Host "$sha  $Message" -ForegroundColor Green

    if ($Todo) {
        foreach ($plan in @(
            'plans/08-worry-postponement.md',
            'plans/09-journaling.md'
        )) {
            if (-not (Test-Path $plan)) { continue }
            $text = Get-Content $plan -Raw
            if ($text -match [regex]::Escape("pending-$Todo")) {
                $text = $text -replace [regex]::Escape("pending-$Todo"), $sha
                Set-Content $plan $text -NoNewline
                Write-Host "      $plan  $Todo -> $sha" -ForegroundColor DarkGray
            }
        }
    }
}

# ---------------------------------------------------------------------------
# Toolchain corrections found by `expo prebuild`.
#
# expo-crypto was pinned ~15.0.7 and expo-localization ~17.0.7 -- both wrong
# majors for SDK 57. These are committed first and separately so they can be
# reverted alone if the lockfile churn is unwelcome.
# ---------------------------------------------------------------------------

Commit-Step -Paths @('apps/native/app.json', 'apps/native/package.json') -Message @'
fix(deps): correct sdk 57 versions and add missing config plugins

expo prebuild reported expo-crypto pinned at ~15.0.7 and expo-localization at
~17.0.7, both wrong majors for SDK 57, plus patch drift on expo, expo-router,
react-native, reanimated and worklets. It also added the expo-localization and
expo-router config plugins, which were absent.

android.package is left as prebuild wrote it (com.anonymous.calma). It needs an
owner decision before anything is distributed -- an Android package name cannot
be changed after a Play Store release without shipping a different app.
'@

Commit-Step -Paths @('pnpm-lock.yaml') -Message @'
chore(deps): relock after sdk 57 version corrections

Side effect of the previous commit. Large and nobody asked for it, so it is on
its own and can be reverted alone.
'@

Commit-Step -Paths @(
    'apps/native/app.json',
    'apps/native/assets/images'
) -Message @'
feat(assets): wire the full icon and splash set, and set the bundle id

Points app.json at every delivered asset. The paths in the asset spec are
./assets/*; the files actually live in ./assets/images/*, so every one of them
is rewritten.

bundleIdentifier and package are now app.calma.mobile, replacing the
com.anonymous.calma placeholder prebuild wrote. This closes an open item that
had to be settled before anything was distributed -- an Android package name
cannot be changed after a Play Store release without shipping a different app.
The generated apps/native/android is now stale and must be re-prebuilt.

icon.png and ios-icon-light.png shipped as RGBA. The spec requires them
opaque, and App Store Connect rejects an iOS icon carrying an alpha channel at
submission. Both were alpha 255 everywhere, so they are flattened onto white
-- visually identical, valid at submission.

expo-splash-screen is configured as a plugin for the first time: it was a
dependency but was never declared, so no splash configuration was being
applied at all. 240pt icon on #FBF7F1, with the dark pair on #141C26.

expo-notifications is NOT added, though the asset spec asks for it. The
package is not a dependency and declaring a plugin for an uninstalled module
fails prebuild. notification-icon.png is delivered and unreferenced until
plan 12 T02 installs the dependency, which is where the plugin block belongs.
'@

Commit-Step -Paths @('.gitignore') -Message @'
chore(git): ignore the prebuild output

apps/native/android and ios are generated by expo prebuild. CNG owns them;
they are regenerated rather than edited, and a committed copy goes stale in a
way nobody notices until a native build behaves differently from a clean one.
'@

# ---------------------------------------------------------------------------
# Tokens. Everything downstream needs these, so they land first.
# ---------------------------------------------------------------------------

Commit-Step -Todo 'T04' -Paths @(
    'packages/tokens/src/colors.ts',
    'packages/tokens/src/layout.ts',
    'packages/tokens/src/tailwind.ts',
    'apps/native/global.css'
) -Message @'
feat(tokens): add the worry and writing grounds

The third session running to find a ground missing from the token layer, and
the pattern is now clear: a feature gets its own ground, the ground gets its
own surface and border pair, and the tokens only learn about it when someone
opens the design file. Session 9 found --immersive, session 10 found
--surface-quiet, this one found two more.

  --worry  #F6EDE3 / #1A1D24   f1-f7, with its own surface, border and quiet
                               button pair. --surface-clay-quiet parts company
                               from the neutral pair in dark mode only.
  --write  #FAF4E9 / #151D26   g0-g6, with paper surfaces and a DASHED draft
                               pair -- a draft is distinct without being an
                               error state.

Also --window-ground (f4 only, which has a stated reason to differ), --sage
and --sage-ring (f6 only), the clay ring/ink/on/placeholder set, a clay
gradient, the window lamp, radius.note (26), control.compact (54),
control.fork (66), and --font-serif-italic.

The italic is a REGISTERED FACE, not fontStyle. Neither platform synthesises
an oblique for a custom family, so asking for italic on Newsreader returns the
upright face on iOS and can fall back to a system serif on Android, silently.
Same trap as font-medium.

A judgement call, recorded in plans/08 T04: the six worry screens carry four
light grounds and one dark ground. Dark agreeing exactly while light varies
non-monotonically reads as hand-tuning, so they are normalised to f1's value.
Reversible in three token names.

All three files move together, so the parity test still spans the gap.
'@

# ---------------------------------------------------------------------------
# Plan 08 -- worry postponement.
# ---------------------------------------------------------------------------

Commit-Step -Todo 'T06' -Paths @(
    'packages/domain/src/worry',
    'packages/domain/src/index.ts'
) -Message @'
feat(worry): add guided triage state machine

Pure, serialisable, and holding ids rather than text. The window survives the
app being killed -- someone opens it at 8pm, gets three worries in, and closes
the phone -- so position has to be data rather than component state.

Nothing here holds worry text. A resumable structure containing everything
someone was afraid of is exactly the artefact this feature exists to avoid
creating, so the queue is ids and the screen reads one at a time.

There is no skip, and nowhere to put one: f5 is a fork, not a recommendation,
and a third option would make avoidance free. There is also no total and no
progress fraction, per f4.

reconcile() re-anchors a restored window on outcomes rather than on the cursor
index. Keeping the index would silently skip a worry every time one vanished
from the queue behind the window back. There is a test for that specific bug,
because it is invisible when it happens.

24 assertions, none of which have ever executed -- vitest has no linux rollup
binary in the sandbox.
'@

Commit-Step -Todo 'T13' -Paths @(
    'apps/native/src/features/worry/schedule.ts',
    'apps/native/src/features/worry/schedule.test.ts',
    'packages/i18n/src/format.ts'
) -Message @'
feat(worry): add window scheduling and carry-over behaviour

The window is a wall-clock time, not an instant. 19:00 means seven in the
evening wherever the person is, whatever the clocks did last night, so every
question goes through local calendar fields and tomorrow is shiftDayKey rather
than +24h. That one line is the whole DST fix: a 23-hour day produces a
23-hour gap and the window still lands at 19:00.

Nothing is cached across calls, so stepping off a plane recomputes rather than
replaying or skipping a window. There is no stored "next window at" instant
that could disagree with the clock, and that absence is the design.

Two availability states, waiting and open, and deliberately no third. A window
that could be missed would make this a chore with a deadline, which is the
specific thing worry postponement relieves. There is a test asserting the
union stays two members, which is where the tone conversation should start if
anyone adds one.

Also adds formatWindowTime to @calma/i18n: drops the minutes on the hour,
because ":00" in running prose reads like a timetable.
'@

Commit-Step -Todo 'T01' -Paths @('apps/native/src/features/worry/store.ts') -Message @'
feat(worry): add worry zustand store

The store holds pendingIds, never Worry objects. The Worries tab renders the
length and there is no data path to anything else -- f1 forbids previews and
first lines, and the way to keep that true in a year is to make the
alternative not exist rather than to write it down.

Window state mirrors into state:worryWindow on every transition. The store is
the working copy; the key is the record.
'@

Commit-Step -Todo 'T02' -Paths @(
    'apps/native/src/features/worry/CaptureField.tsx',
    'apps/native/src/features/worry/ClayFill.tsx',
    'apps/native/src/features/worry/Ripple.tsx'
) -Message @'
feat(worry): build quick-capture input with confirmation

The field is never blocked, and that is the requirement everything else bends
around. A spiral produces worries three seconds apart, not thirty, so the
order inside submit is: read the text, clear the input, write, then animate.
The dissolve, the pebble and the sentence all play over a field that is
already accepting the next worry.

Submit is idempotent for 600ms so a lagging double tap cannot store the same
worry twice and corrupt the pending count -- which is the only number this
feature shows anyone.

T03 wants the text to dissolve upward over 900ms and T16 wants the field live
instantly; both cannot be literally true once the input is cleared on the
submit tick. f3 settles it ("a ripple settling where it was", and the design
shows rings and no words): the upward travel belongs to the ripple and the
sentence. Recorded in plans/08 T03.

The submitted text is never rendered back. A worry echoed into a confirmation
has not been postponed, it has been repeated.
'@

Commit-Step -Todo 'T04' -Paths @(
    'apps/native/src/features/worry/WorriesScreen.tsx',
    'apps/native/app/(tabs)/worries.tsx',
    'packages/i18n/src/locales/en/worry.json',
    'apps/native/src/features/home/HomeScreen.tsx'
) -Message @'
feat(worry): build worries tab screen

Count as a sentence, never a badge, and never the largest thing on screen. No
list, no previews, and no component that could become one.

The field sits above the count so writing never means scrolling past what is
already there -- someone arriving mid-spiral lands on the input, not on a
tally of how much they are carrying.

"Open it now" appears only once the window has opened and something is
waiting. No disabled state and no countdown: D-008 forbids framing the wait as
a deadline, and a greyed button with a timer under it is exactly that.

Also fixes a live bug on Home. worry:windowIn read "Your window opens in
{{duration}}" and was being handed a clock time, so it rendered "opens in 7:00
PM". f1 says "at", the value was always a time, and only the key was wrong.
'@

Commit-Step -Todo 'T08' -Paths @(
    'apps/native/src/features/worry/WorryWindowScreen.tsx',
    'apps/native/src/features/worry/TriageQuestion.tsx',
    'apps/native/src/features/worry/TriageAction.tsx',
    'apps/native/src/features/worry/TriageRelease.tsx',
    'apps/native/src/features/worry/WindowSummary.tsx',
    'apps/native/app/worry-window.tsx',
    'apps/native/app/_layout.tsx',
    'apps/native/src/ui/Text.tsx',
    'apps/native/src/lib/haptics/index.ts'
) -Message @'
feat(worry): build the worry window and its four steps

Full screen, no tab bar, and no route to a capture field from inside it. f4
forbids adding worries here, and the reason is that a queue which grows while
you work through it never ends.

No total and no progress indicator anywhere. queue.length is right there and
is never rendered.

f5 -- their words are the largest thing on screen, set in the serif, never
truncated. Two identical buttons: same height, fill, border, weight and order.
The app does not know which answer is right for this worry, so styling one as
primary would be a guess rendered as advice.

f6 -- sage enters here and nowhere else in the app, as a border and a caret,
never a fill and never text. A green tick would make this a success state, and
Calma has nothing to be right about. The empty path gets its own words,
"Nothing comes to mind", per the caption rather than per the todo.

f7 -- a real gesture, not a button, because releasing by tap would feel
administrative. The card disperses upward rather than travelling somewhere: it
does not go anywhere, it stops being a thing. An incomplete swipe springs back
to exactly where it was, so the only way to release is to mean it, and there
is no undo. The gesture is also an activatable control, because VoiceOver
cannot swipe a card past a threshold and a release reachable only by hand
would exclude the people most likely to be using a screen reader in the dark.

f8 -- sentences, not a chart. Three copy variants, because "0 were within your
control" is the register of a form. The closing question is italic and has no
field under it: a pause, not an input.
'@

# ---------------------------------------------------------------------------
# Plan 09 -- journaling's spine.
# ---------------------------------------------------------------------------

Commit-Step -Todo 'T01' -Paths @(
    'apps/native/src/features/journal/store.ts',
    'apps/native/src/features/journal/steps.ts'
) -Message @'
feat(journal): add journal store and the thought-record step table

An entry is a draft on disk from before its first keystroke, so there is no
window in which someone writing lives somewhere a force-quit can take it.

Unlike the worry store this one holds text, and the contrast is the point: a
worry is set down to stop thinking about, an entry is written to be returned
to. Same principle, opposite features.

The six prompts are a table rather than six near-identical components. Five of
them differ only in prompt, hint and target field, and six components is five
more places for a "required" flag to appear later. The table has nowhere to
put one.
'@

Commit-Step -Todo 'T06' -Paths @('apps/native/src/features/journal/useAutosave.ts') -Message @'
feat(journal): add continuous draft autosave

A half-written journal entry is the most emotionally costly thing this app
holds. Losing one is worse than a crash, because a crash does not take
anything with it.

So saving is continuous and debounced at 800ms, not on blur. Blur-only saving
loses everything typed into the field that was focused when the phone was
killed -- which is, by definition, the field they were in the middle of.

Three overlapping triggers: the debounce, AppState leaving active (the last
code that runs before iOS may suspend and then kill), and unmount. The dirty
buffer is cleared before the await, so keystrokes landing during a write are
recorded as newly dirty rather than wiped by the completion of a save that did
not include them.
'@

Commit-Step -Todo 'T02' -Paths @(
    'apps/native/src/features/journal/EditorScreen.tsx',
    'apps/native/src/features/journal/IntensityScale.tsx',
    'apps/native/app/journal'
) -Message @'
feat(journal): build the entry editor and intensity control

No code path in the editor clears it. Not on save, not on error, not on
navigation, not on reaching a limit. A hit weekly limit or a paywall blocks
the finish, never the writing, and the draft is still there afterwards.

Save is idempotent for 600ms so a lagging tap cannot create a duplicate entry
or burn two weekly allowances.

The intensity control is eleven tappable marks, not a slider. The SUDS slider
is dragged mid-spiral with one thumb; this is answered sitting still, and a
slider there invites fiddling with a number that does not deserve precision.
No colour ramp and no labels beyond the ends, because a green-to-red scale
would make 8 a failing grade.

Emotion and intensity are one step. "Anxious" and "how strong" are a single
act of noticing; splitting them makes the second a quiz about the first. Free
text, no fixed list -- a vocabulary tells someone their feeling is not on the
menu.
'@

Commit-Step -Todo 'T12' -Paths @(
    'apps/native/src/features/journal/WriteScreen.tsx',
    'apps/native/app/(tabs)/write.tsx',
    'packages/i18n/src/locales/en/journal.json'
) -Message @'
feat(journal): build the write tab

Starting to write is the largest thing on the screen and does not move down as
the archive grows. Someone opening this tab because they need to write now
must not scroll past their own history to do it -- an archive that leads turns
a writing tool into a record of how much you have written.

No count, no quota, no target, anywhere. weekCount exists in the store for the
tier check and is deliberately not read here.

Drafts are dashed and nothing else. Distinct without being an error.

g0 sets its section labels in IBM Plex Mono; Calma ships two typefaces and a
third would be a third voice, so they use the sans caption variant with the
design tracking. Recorded in plans/09 T12.
'@

Commit-Step -Paths @('apps/native/app/_layout.tsx') -Message @'
fix(nav): send a first launch to onboarding

The first-run decision was initialRouteName={firstRun ? 'onboarding' :
'(tabs)'} as a prop on <Stack>. That prop decides nothing here: expo-router
derives a layout's screens from the filesystem and takes the initial route
from unstable_settings, which is hard-coded to '(tabs)'.

So the ternary read as if it worked, type-checked, and would have sent every
first launch straight to Home. Ten onboarding screens -- an entire plan --
would have been unreachable code behind a flag that never fired, with nothing
erroring and nobody seeing a welcome screen.

Replaced with an imperative replace() issued once, before the splash comes
down. replace rather than push so there is no Home underneath to go back to:
onboarding is where the app starts, not somewhere it navigated to.

The splash now waits on the routing decision rather than on layout alone.
Without that a first launch paints one frame of the Home tab first, which is a
glimpse of a product someone has not been introduced to yet.

NOT VERIFIED ON A DEVICE. Clear prefs, launch, and confirm you land on Welcome
with no flash of the tab bar.
'@

# progress/ is gitignored, so nothing below is committed. Listed here only so
# the next session knows the handover docs were rewritten:
#   progress/03-screens-status.md  all 58 screens, plus the handover order
#   progress/00-START-HERE.md      rewritten, points at the screen table
#   progress/04-changelog.md       session 11 entry

Write-Host ''
Write-Host 'Done. Next:' -ForegroundColor Cyan
Write-Host '  pnpm install        # REQUIRED -- dependency versions changed'
Write-Host '  pnpm check-types'
Write-Host '  pnpm test           # first run ever; expect real failures'
Write-Host '  pnpm dev:native'
